# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# License:    GPL
# File Name:  ./Makefile
# Build Date: Tue Nov 14 04:08:48 PM CST 2023
# Version:    0.0.1

CXX = g++
CXXFLAGS = -Wall -std=c++17 -DDEBUG -g
APPNAME = @@APP_NAME@@
BUILD = build
OBJ =  build
SRC = src

debug: all

all: @@APP_NAME@@

@@APP_NAME@@: @@APP_NAME@@.o main.o #@@PREREQUISTE@@
	 $(CXX) $(CXXFLAGS) $(BUILD)/@@APP_NAME@@.o $(BUILD)/main.o -o $(BUILD)/@@APP_NAME@@ #@@CLASS_NAME@@

@@APP_NAME@@.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/@@APP_NAME@@.cpp -o $(BUILD)/@@APP_NAME@@.o
	
main.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/main.cpp -o $(BUILD)/main.o

#AUTO_INSERT_POINT_DO_NOT_REMOVE#

clean:
	-rm -f $(OBJ)/*.
	-rm -f $(BUILD)/*
	